export default {
    portraitObj: [{
        age: '20~25',
        maritalStatus: '未婚',
        areaStr: '太原',
        equipment: '安卓',
        education: '专科',
        personalityType: '完美型',
        personalityDes: '有极强的原则性、不易妥协、常说“应该”及“不应该”、黑白分明、对自己和别人要求甚高、追求完美、不断改进、感情世界薄弱'
    }, {
        age: '20~25',
        maritalStatus: '已婚',
        areaStr: '天津',
        equipment: 'ios',
        education: '专科',
        personalityType: '助人型',
        personalityDes: '渴望别人的爱或良好关系、甘愿迁就他人、以人为本、要别人觉得需要自己、常忽略自己'
    }, {
        age: '20~25',
        maritalStatus: '未婚',
        areaStr: '北京',
        equipment: '安卓',
        education: '本科',
        personalityType: '成就型',
        personalityDes: '强烈好胜心，喜欢权威，常与别人比较，以成就衡量自己的价值高低，注重形象，工作狂，惧怕表达内心感受'
    }, {
        age: '20~25',
        maritalStatus: '已婚',
        areaStr: '郑州',
        equipment: 'ios',
        education: '本科',
        personalityType: '自我型',
        personalityDes: '情绪化，追求浪漫，惧怕被人拒绝，觉得别人不明白自己， 占有欲强，我行我素的生活风格'
    }, {
        age: '25~30',
        maritalStatus: '未婚',
        areaStr: '深圳',
        equipment: '安卓',
        education: '硕士',
        personalityType: '理智型',
        personalityDes: '冷眼看世界，孤僻，喜欢远离人群，抽离情感，喜欢思考分析，想知道的很多，但缺乏行动，对物质生活要求不高，喜欢精神生活，不善表达内心感受'
    }, {
        age: '25~30',
        maritalStatus: '已婚',
        areaStr: '青岛',
        equipment: 'ios',
        education: '硕士',
        personalityType: '忠诚型',
        personalityDes: '做事小心谨慎，不轻易相信别人，多疑虑，喜欢群体生活，为别人做事尽心尽力，不喜欢受人注视，安于现状，不喜欢转换新环境'
    }, {
        age: '30~35',
        maritalStatus: '已婚',
        areaStr: '合肥',
        equipment: '安卓',
        education: '博士',
        personalityType: '活跃型',
        personalityDes: '乐观，要新鲜感，追上潮流，不喜欢承受压力，怕负面情绪；想过愉快的生活，想创新、自娱娱人，渴望过比较享受的生活，把人间的不美好化为乌有'
    }, {
        age: '30~35',
        maritalStatus: '已婚',
        areaStr: '上海',
        equipment: 'ios',
        education: '博士',
        personalityType: '领袖型',
        personalityDes: '追求权力，讲求实力，不靠他人，有正义感。要话事（说的算），喜欢做大事9、和平型：须花长时间作决定，难于拒绝他人，不懂宣泄愤怒；显得十分温和，不喜欢与人起冲突，不自夸、不爱出风头，个性淡薄'
    }]
}